language: node_js
node_js:
  - "8.8.1"
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/

jobs:
  include:
    - stage: build
      install: npm install
      script: npm run build:run
    - stage: test
      install: npm install
      script: npm run test
