# General settings
dist: trusty
sudo: false
language: node_js
node_js:
  - "8.8.1"
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/

# Build stages
stages:
  - name: build
  - name: test
  - name: release
    if: branch = master

# Build jobs
jobs:
  include:
    - stage: build
      install:
        - npm install
      script:
        - npm run build:run
    - stage: test
      install:
        - npm install
      script:
        - npm run test
    - stage: release
      before_install:
        - git clone "https://github.com/$TRAVIS_REPO_SLUG.git" "$TRAVIS_REPO_SLUG"; # We also need the develop branch
        - cd "$TRAVIS_REPO_SLUG";
        - git checkout -qf "$TRAVIS_COMMIT";
        - git checkout master # Fix Travis CI issue of detached head in git
      install:
        - npm install
      script:
        - npm run build:run
        - npm run build:copy
      before_deploy:
        - git config --global user.name "dominique-mueller";
        - git config --global user.email "dominique.m.mueller@gmail.com";
        - git config credential.helper "store --file=.git/credentials";
        - echo "https://$GH_TOKEN:@github.com" > .git/credentials;
        - npm run release # Run itself
        - npm run post-release # Copy updates package and changelog files
        - cd dist # Publish from the dist folder
      deploy:
        provider: npm
        email: dominique.m.mueller@gmail.com
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
      after_deploy:
        - cd ..
        - npm run list-published-files
