# General settings
dist: trusty
sudo: false
language: node_js
node_js:
  - "8.8.1"
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/

# Build stages
stages:
  - name: build
  - name: test
  - name: release
    if: branch = master

# Build jobs
jobs:
  include:
    - stage: build
      install: npm install
      script: npm run build:run
    - stage: test
      install: npm install
      script: npm run test
    - stage: release
      install: npm install
      script: echo "Release"
