language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false

branches:
  only:
    - master

deploy:
  provider: npm
  email: dominique.m.mueller@gmail.com
  api_key: "${NPM_TOKEN}"
  on:
    branch: master
    repo: dominique-mueller/automatic-release
